---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: emacs24
    run_list:
      - recipe[emacs24]
    attributes:
      emacs24:
        version: 24.3
        build_dir: /opt/emacs
