---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6
  - name: ubuntu-12.04

suites:
  - name: emacs24
    run_list:
      - recipe[emacs24]
    attributes: {
      emacs24: {
        build_dir: "/opt/emacs"
      }
    }
